# https://rust-lang.github.io/rustfmt/
tab_spaces                 = 2
fn_call_width              = 80
max_width                  = 90
group_imports              = "StdExternalCrate"
reorder_impl_items         = true
overflow_delimited_expr    = true
use_field_init_shorthand   = true
use_try_shorthand          = true
wrap_comments              = false
condense_wildcard_suffixes = true
imports_granularity        = "Crate"
imports_layout             = "HorizontalVertical"
